### ISSUE TITLE
我应该比你短……（手动滑稽

### ISSUE THREAD

**Issue by iwestlin** [xenv/teenyBlog#1]
如果不算各种依赖的话。。 https://github.com/iwestlin/message-board/blob/master/public/write.html
用firebase做后端，支持无限加载、markdown渲染、实时同步以及登录功能……

然而由于firebase被墙，所以用node做了个转发。
主页 https://talk.viegg.com/

**Comment by xenv** [comment]
确实不错，不过，算上main.css（我没有外链css），还是不算短，哈哈
